# This is a basic workflow to help you get started with Actions

name: Environment config

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Fulano
      url: https://www.geofisicando.com
    
    steps:
      - name: Run a one-line script
        run: echo ${{env.MEU_AMBIENTE}}
