# This is a basic workflow to help you get started with Actions

name: Self Hosted Runner

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  self-hosted-test:
    runs-on: ['metadata','extractor']

    steps:
      - name: Run a one-line script
        run: |
          echo Hello, world!
          pwd
          ls
