# This is a basic workflow to help you get started with Actions

name: Share variables

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      output1: ${{steps.step1.outputs.var1_name}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: step1
        run: echo "::set_output name=var1_name::Rodolfo"

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: step2
        run: echo "Variavel ${{needs.build.outputs.output1}}"
