# This is a basic workflow to help you get started with Actions

name: Share variables

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      output1: ${{steps.step1.outputs.var1}}
      output2: ${{steps.step2.outputs.var2}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: step1
        run: |
          echo "::set-output name=var1::Rodolfo"
          echo Setei ${{env.var1}}
      - id: step2
        run: |
          echo "::set-output name=var2::Importante"

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: step2
        run: |
          echo "Print vars"
          echo "Variavel ${{needs.build.outputs.output1}}"
          echo Variavel2: ${{needs.build.outputs.output2}}
